### ISSUE TITLE
Fatal error while testing tutorial example (step 2)

### ISSUE THREAD

**Issue by schumi2k2** [joomla/Joomla-3.2-Hello-World-Component#3]
Hello,

I'm new in Joomla! components developement.

I'm reading your tutorial to create components for Joomla 3.2 at http://docs.joomla.org/J3.2:Developing_a_MVC_Component/Adding_a_view_to_the_site_part

The example for step 2 (Developing a MVC Component/Adding a view to the site part) is not working.

Steps to reproduce :
- install default joomla 3.2.1 release (french version, but irrelevant in my opinion)
- download archive exemple given in tutorial (bottom of the page)
- install it from backend (install is successfull)
- test the component by accessing http://localhost/index.php?option=com_helloworld

Following error is raised :

Fatal error: Call to undefined method JController::getInstance() in <blablabla>\components\com_helloworld\helloworld.php on line 20

![error](https://f.cloud.github.com/assets/6673487/2161377/9d9f9b60-94c5-11e3-909c-e78463af2e4d.png)
![tutorial](https://f.cloud.github.com/assets/6673487/2161378/9da29a40-94c5-11e3-856f-c3d48fc72ede.png)

**Comment by schumi2k2** [comment]
Sorry for closing / reopening this issue, this is my first post on GitHub, discovering interface :-)

**Comment by wbommel** [comment]
The problem in the downloadable archive is that the extends still point to old classes like `JController`, `JView` and not to the new `JControllerLegacy`, `JViewLegacy`.
To work around this issue, just take a look in the archives of the next chapters.

Other than that, if you can fix this issue by yourself you are on a good way to understand the joomla concepts. ;)

**Comment by Hutchy68** [comment]
Closing the doc now points here the correct archive for the associated files.
